const FORWARDING_OPTIONS = {
    FORWARD_CALL: 1,
    RECORD_VOICE: 2
}

const VOICE_MAIL_STATUS = 'voice'
const AGENT_STATUS = 'agent'

export { FORWARDING_OPTIONS, VOICE_MAIL_STATUS, AGENT_STATUS }
